# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
warnings_are_errors: true
sudo: true

r_packages: 
 - mapview
 - sf

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  
addons:
    apt:
        packages:
            - libudunits2-dev
            - libproj-dev
            - libgeos++-dev
            - libgdal-dev
            - libgeos-dev
matrix:
    include:
        - os: linux
          r: release
          dist: trusty # 14.04
          env:
           - BUILD_NAME=trusty_release
           - DETAILS="release build"
        - os: osx
          r: release
          env:
           - BUILD_NAME=osx_release
           - DETAILS="release build"

notifications:
  email:
    on_success: change
    on_failure: change

#r_github_packages:
#      - jimhester/covr


after_success:
  - Rscript -e 'covr::codecov()'
