---
title: "Southern Ocean Coastal"
author: "Michael Sumner"
date: "`r Sys.Date()`"
output:
  rmarkdown::html_vignette:
    fig_width: 11
    fig_height: 9
vignette: >
  %\VignetteIndexEntry{socoastal}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

This shows loading the package and creating an interactive map, with some available data layers. 

* **ibcso**:  http://www.ibcso.org/data.html
* **gebco**: https://www.gebco.net/


```{r}
library(socoastal)
library(mapview)
library(sf)
layers <- st_sf(name = c("ibcso", "gebco", "scar"), type = c("bathymetry", "bathymetry", "coastline"), 
                geometry = c(ibcso_500, gebco_500, scar_0))
m <- mapview(layers, zcol = "name", 
             color = c("#440154FF", "#21908CFF", "#000000FF"), 
             legend = TRUE,
             ## http://leaflet-extras.github.io/leaflet-providers/preview/
             map.types = c("Esri.NatGeoWorldMap", "Esri.OceanBasemap", "Esri.WorldPhysical", "CartoDB.DarkMatter", "OpenStreetMap",      "Esri.WorldImagery" ))
m
```
